- debconf: name=debconf question='mysql-server/root_password' value='{{mysql_root_password}}' vtype=string
- debconf: name=debconf question='mysql-server/root_password_again' value='{{mysql_root_password}}' vtype=string

- apt: name={{item}}
  with_items:
    - nginx
    - mysql-server
    - zip
    - git
    - pwgen
    - php5-fpm
    - php5-gd
    - php5-apcu
    - php5-mysql
    - php5-cli
    - php5-curl
    - php5-imagick
    - python-mysqldb
    - python-httplib2

- file: path=/etc/php5/fpm/pool.d/www.conf state=absent
- file: path=/etc/nginx/sites-enabled/default state=absent

- include: postfix.yml
