---
- command: fallocate -l {{swap_size}} /swapfile
  when: ansible_swaptotal_mb < 1
- command: mkswap /swapfile
  when: ansible_swaptotal_mb < 1
- name: add swap to fstab
  lineinfile: dest=/etc/fstab regexp="swapfile" line="/swapfile none swap sw 0 0" state=present
- command: swapon -a
  when: ansible_swaptotal_mb < 1
- sysctl: name=vm.swappiness value=1
- sysctl: name=vm.vfs_cache_pressure value=50